#! /bin/bash
#
# Usage: "./check"
#

for src in `ls expect/*`; do
   srcname=`basename ${src}`
   echo "Diff'ing expect/${srcname} and actual/${srcname}"
   diff expect/${srcname} actual/${srcname}
done
